Stages
DemocraciaEnRed/vicentelopez pull request #391
Opened 2022-09-20 16:45 UTC by xtian7489

Se agrega una nueva sección en el administrador llamada configuración, para dar más autonomía a la hora de abrir y cerrar propuestas y votaciones. Para esto se creó en la colección fórum la sección llamada "config" con distintos campos, como ser, PropuestasAbiertas, Pre-votación, LinkVotaciones, etc. para estos nuevos campos se creó una migración para su inicialización, tomando los que existían en el archivo config como predeterminados.

Se modificó también las distintas invocaciones como config.propuestasAbiertas a forum.config.propuestasAbiertas, para que funcionen con este nuevo campo en el documento fórum.
Se agregan botones con un link para el redireccionamiento de hacia la plataforma de votación con la que cuenta el municipio.

Se automatiza la sección de proyectos, dando 3 estados(pre-votación, votacion finalizada y seguimiento normal) donde en el primer estado se muestra:
      de un lado los proyectos a votar(o sea proyectos factibles con fecha del año entrante)
       y del otro lado los proyectos ganadores de votaciones anteriores
con el estado de votación finalizada:
      de un lado los proyectos ganadores y no ganadores del año entrante(o sea proyectos ganadores de la votación)
      y del otro lado igual que en votación proyectos ganadores de votaciones anteriores
y con un tercer estado que seria seguimiento normal:
      todos los proyectos ganadores

2022-09-22 14:50 UTC, guillecro commented on ext/lib/site/header/component.js
> +            <a href={forum.config.linkVotaciones}>vota</a>
Label deberia decir "Votá" con el tilde

2022-09-22 15:08 UTC, guillecro requested changes
Gracias @xtian7489 por los commits, excelente el laburo de migracion, cambios en el modelo. Me gusto como manejaste api, dbapi y el armado del panel de admin para todo esto.

Deje comentarios, cosas a tener en cuenta, capas algunos agregados que habria que hacer sobre el config del foro.

Se me ocurre que capas tambien estaria bueno otras opciones a agregar al foro pero sigamos con los requerimientos pedidos, asi no cambiamos el scope y no tenemos intenciones repartidas, Jajaja.

2022-09-22 15:08 UTC, guillecro commented on ext/lib/site/home-proyectos/component.js
> +        initialFilters.anio = '2018,2019,2020,2021,2022'
Esto deberia ser similar a 

`this.props.location.query.stage === 'seguimiento' ? '2018,2019,2020,2021,2022' : '2023'`

O sea... 

`this.props.location.query.stage === 'seguimiento' ? previousYears.join(',') : currentYear`

2022-09-22 15:08 UTC, guillecro commented on ext/lib/site/home-proyectos/component.js
>    componentDidMount () {
Este metodo es el mas complejo de ver. Lo podemos analizar en profundidad, armar una especie de diagrama de flujo

2022-09-22 15:08 UTC, guillecro commented on ext/lib/site/home-proyectos/component.js
> +        anio: newStage === 'seguimiento' ? ['2018', '2019', '2020', '2021', '2022'] : ['2023']
Tambien, habria que ver como se automatiza estos arrays de años anteriores y el `currentYear`

2022-09-22 15:08 UTC, guillecro commented on ext/lib/site/proyectosFactibles/component.js
> +    window.fetch(`/ext/api/topics?forumName=proyectos&anio=2023&state=factible&limit=30&sort=popular`, { credentials: 'include' })
posibilidad de sacar el año actual desde el forum (ver)

2022-09-22 15:08 UTC, guillecro commented on ext/lib/site/proyectosGanadores/component.js
> +    window.fetch(`/ext/api/topics?forumName=proyectos&anio=2023&state=preparacion,compra,ejecucion,finalizado&limit=100&sort=popular`, { credentials: 'include' })
Idem, ver de sacar del forum el año actual

2022-09-22 15:08 UTC, guillecro commented on ext/lib/site/thumbs-voto/component.js
> +                <a href={props.forum.config.linkVotaciones}>vota aqui</a>
capas faltaria el `target="_blank"`

2022-09-22 15:08 UTC, guillecro commented on migrations/2000000000005-add-config-at forum.js
> +        forumProyecto.config = {}
Se puede hacer en otra migracion si queres, o pisar esta. Mejor en otra asi te funciona a vos y no tenes que sumarlo a pata en tu DB

2022-09-22 15:17 UTC, xtian7489 commented on ext/lib/site/home-propuestas/component.js
> +            { forum && forum.config.propuestasTexto &&
buenas Guillermo, se lo cambio para que sea un solo texto para propuestas abiertas y propuestas cerradas, entonces al ser un solo texto verifica si existe el texto lo agrega si no no, viendolo mas a detalle se podria poner la verificacion antes en el div.container

2022-09-22 15:21 UTC, xtian7489 commented on migrations/2000000000005-add-config-at forum.js
> +        forumProyecto.config = {}
lo habia pensado para mas adelante, que el municipio agregue el año de votacion, entonces en el home-proyecto hacer esto:
completeYears () {
    const dt = new Date()
    const nextCurrentYearToOperate = dt.getFullYear() + 1
    for (let i = 5; i >= 0; i--) {
      fiveYearNotCurrent.push((nextCurrentYearToOperate - i).toString())
    }
    fiveYearNextCurrent.push(...fiveYearNotCurrent)
    nextYear.push(fiveYearNotCurrent.pop())
    currentYear.push(...fiveYearNotCurrent.slice(-1))
  }
  
de hecho se me colaron en el commit esas variables 

let fiveYearNotCurrent = []
let fiveYearNextCurrent = []
let currentYear = []
let nextYear = []

2022-09-22 15:22 UTC, xtian7489 commented on migrations/2000000000005-add-config-at forum.js
> +        forumProyecto.config = {}
ahi toma el año con el Date de javascript, pero lo podriamos adaptar para que tome el año que introduzca el municipio

2022-09-22 15:33 UTC, xtian7489 commented on ext/lib/site/header/component.js
> +            <a href={forum.config.linkVotaciones}>vota</a>
ok, aqui tambien agrego  target='_blank'?

2022-09-27 13:08 UTC, guillecro commented on migrations/2000000000005-add-config-at forum.js
> +        forumProyecto.config = {}
Capas a futuro podemos agregar esto, podria ser interesante. Capas de ultima puede ser (no se como seria en mongoose) pero un atributo autocalculado del modelo "forum".

Podria ser interesante, pero me parece bien lo que propones.

2022-09-27 13:09 UTC, guillecro approved these changes
Mergeamos a master! Gracias @xtian7489 !

2022-09-27 13:12 UTC, guillecro commented
Resuelto conflictos y mergeando a master.

2022-09-27 13:12 UTC, merged